### PR TITLE
Suppress 1591 warning at project level

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
This PR is more about removing timeouts from a test. Split please.

**Comment by MikhailTymchukDX** [comment]
Done: #146

**Comment by AlekseyMartynov** [comment]
Ok now we are going to remove all of this, aren't we?
https://github.com/DevExpress/AjaxControlToolkit/search?q=1591

**Comment by MikhailTymchukDX** [comment]
Sure: https://github.com/DevExpress/AjaxControlToolkit/pull/145/commits/72af03280f8423942f4d6297ae09a030fed66b47

**Comment by AlekseyMartynov** [comment]
:shipit:

**Pull request merged**
