### PR TITLE
Resolve #109

### LINKED ISSUE #109: HtmlEditorExtender give focus problems
Hello,
I have the following construction.
- Normal textbox
- Textbox with HtmlEditorExtender (= Editor)

I have an updatepanel with a label and a timer. This timer will update the updatepanel.

Issue 1: I set the focus in the normal textbox. After the partial postback the focus is set to the Editor in stead of the normal textbox.
Issue 2: I have text in the Editor, and the cursor is at the end. After the partial postback the focus is set at the start of the Editor.

In ff the behavior is as expected:
Issue 1: The cursor is still in the normal textbox.
Issue 2: The cursor is at the end of the Editor.

I thought this was only the case in Chrome, but I see that this is also for IE and Safari.

Had anyone a tweak to have Chrome for the cursor behavior.

Any help is welcome.
Looking forward to an answer.

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
I see that you remove a block of code. Any chance that we can find out when it has been added and what was the purpose of that?

**Comment by MikhailTymchukDX** [comment]
`setTimeout` was a dead code that never executed.

Next block was added with this commit: https://github.com/DevExpress/AjaxControlToolkit/commit/5fb193dbbcd19da887e85d639842005dad571396.

The current version of the code moves the cursor to the start of the div.

**Comment by AlekseyMartynov** [comment]
Ok. Merge.

**Pull request merged**
