### PR TITLE
User defined folder for file upload

### PR DESCRIPTION
**Pull request by darilek**
User defined folder for file upload. Useful for using AjaxFileUpload in cluster enviroment

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX 
The use of a mutable static property is potentially unsafe. OK if it's initialized to a constant and never changed, but we cannot guarantee that. Let's change to `HttpContext.Current.Items`.

**Comment by darilek** [comment]
It was meant as initialization using constants at application startup. But content of `HttpContext.Current.Items` must be refreshed on every request. Would be `HttpContext.Current.Application` the right place for storing root path?

**Comment by AlekseyMartynov** [comment]
Hi @darilek 
I see. For static configuration, a key in web.config is perfect.
What do you think?

**Comment by darilek** [comment]
Yes web.config is good place. So by default temp dir will be used with possibility to override via web.config settings. IMHO special new child element for this should be created. What do you think?

**Comment by AlekseyMartynov** [comment]
@darilek 
Sounds good!
We're moving the discussion to https://github.com/DevExpress/AjaxControlToolkit/issues/22

**Comment by IlyaKhD** [comment]
Hi @darilek,
Would you please clarify, does this problem occur when you are using the `SaveAs` method on the `OnUploadComplete`?

The  expected `AjaxFileUpload` usage is:
1) Download a file to the TEMP dir
2) When download completed copy this file to the required destination.

Thus one shouldn't rely on the TEMP dir - it's just a intermediate storage to avoid accessing the file before download completed.


P.S. Sorry for righting in the closed thread

**Comment by AlekseyMartynov** [comment]
@IlyaKhD 
Medium Trust? (see #29)

**Comment by IlyaKhD** [comment]
@AlekseyMartynov 
I mean that `AjaxFileUpload` TEMP path is an internal thing and shouldn't be worked with directly.
As for Medium Trust - I think this problem should be solved globally, like 'fix all GetTempPath() calls'.

**Comment by darilek** [comment]
I wrote the reason for this property in the first post - using `AjaxFileUpload` in cluster enviroment (web farm). You need shared location to assemble file chunks from all servers in cluster. From client side, you don't know which server in cluster processes incoming AJAX request (containing file chunk)

**Comment by IlyaKhD** [comment]
And you farm is working in non sticky mode, right?

**Pull request merged**
