### PR TITLE
CollapsiblePanelExtender - update images even if the target elements have blank src

### PR DESCRIPTION
**Pull request by naster01**
… property declared. If you don't want the target image to be updated just put theses properties to blank inside the CollapsiblePanel (collapsedImage / expandedImage).

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Hi @naster01 

Thanks for the PR.
Would you please describe a scenario in which this change is necessary?

**Comment by naster01** [comment]
When the referenced control (ImageControlID) of the CollapsiblePanel has no source, the picture is left blank. All the behaviours are declared within the CollapsiblePanel, so it makes sense to use thoses. For exemple, the Collapsed property will influence witch picture is shown. So, currently, I have to copy the value of the property CollapsedImage/ExpandedImage depending of the Collapsed value inside the referenced image control's source for the picture to be shown.

Not working : 

    <cc1:CollapsiblePanelExtender 
        ID="cpeDemande" runat="server" TargetControlID="pnlDemandes"
        CollapseControlID="ZoneCliquableDemande" ExpandControlID="ZoneCliquableDemande"
        CollapsedSize="0" ExpandedSize="310" ImageControlID="imgPanelDemande" ExpandedImage="~/Images/collapse.jpg"
        CollapsedImage="~/Images/expand.jpg" SuppressPostBack="False" Collapsed="True"
        Enabled="True">
    </cc1:CollapsiblePanelExtender>

    <asp:Image ID="imgPanelDemande" runat="server" />

Fix : 

    <cc1:CollapsiblePanelExtender 
        ID="cpeDemande" runat="server" TargetControlID="pnlDemandes"
        CollapseControlID="ZoneCliquableDemande" ExpandControlID="ZoneCliquableDemande"
        CollapsedSize="0" ExpandedSize="310" ImageControlID="imgPanelDemande" ExpandedImage="~/Images/collapse.jpg"
        CollapsedImage="~/Images/expand.jpg" SuppressPostBack="False" Collapsed="True"
        Enabled="True">
    </cc1:CollapsiblePanelExtender>

    <asp:Image ID="imgPanelDemande" runat="server" src="~/Images/expand.jpg" />

**Comment by AlekseyMartynov** [comment]
Makes sense.

It seems that the real purpose of `i.src` check is to ensure that referenced elements are `IMG` tags (i.e. they have the `src` attribute defined).

I suggest that we keep this validation but make it work for blank URLs too:

```
if(i && i.tagName === "IMG")
```

Would you please keep original comments and formatting, and only change the condition of `if` statements? You can do that by pushing more commits. A complete diff can be seen here: https://github.com/DevExpress/AjaxControlToolkit/pull/165/files

**Comment by naster01** [comment]
The last commit cannot automatically merge?

**Comment by AlekseyMartynov** [comment]
According to https://status.github.com/messages they have temporary issues. I triggered a re-build.

**Comment by AlekseyMartynov** [comment]
@Seteh please review

**Comment by Seteh** [comment]
Hi @naster01

I agree that the `if(i && i.src)` condition should be clearer, but I wasn't able to reproduce the following behavior:
> When the referenced control (ImageControlID) of the CollapsiblePanel has no source, the picture is left blank.

Here are the steps I performed to reproduce it:

1.  opened `CollapsiblePanel.aspx` file from `AjaxControlToolkit.SampleSite` project;
2.  replaced the `<asp:ImageButton ID="Image1" runat="server" AlternateText="(Show Details...)" />` line with an ASPImage declaration with an empty src atribute value `<asp:Image ID="Image1" runat="server"  />`;
3. run the `AjaxControlToolkit.SampleSite` project.

The expanded/

So your clarification would be helpful.

**Pull request closed without merging**
