### PR TITLE
ColorPicker - Add new Color Palette in option

### PR DESCRIPTION
**Pull request by YoannNivel**

### CODE REVIEW

**Comment by MikhailTymchukDX** [comment]
This may break the experience of existing users, as they will be unable to select a color selected earlier.
Would you please make this feature an option of the extender?

**Comment by YoannNivel** [comment]
No problem, I understand. I'll try to realize this.

**Comment by YoannNivel** [comment]
I added it in option.

**Comment by AlekseyMartynov** [comment]
@YoannNivel 

Thank you for the PR, we appreciate it!
As the changes are relatively massive and include new functionality, we'll evaluate this new feature and decide whether or not to include it, and when.

I leave this PR open.
Feel free to add commits - maybe add a couple of tests? :smile:

**Comment by YoannNivel** [comment]
I'll try to do it next week.

**Comment by MikhailTymchukDX** [comment]
Hi @YoannNivel ,
We imported your valuable commits into the new PR: #208 
If you have new commits, please add them here, so we can cherry pick them preserving your authorship.

**Comment by MikhailTymchukDX** [comment]
@YoannNivel your changes were merged into the master branch.
Thank you again for this improvement!

**Comment by YoannNivel** [comment]
You are welcome.
Sorry for couple of tests, I didn't have time to produce them.

**Pull request closed without merging**
