### PR TITLE
Resolve #136

### LINKED ISSUE #136: AjaxFileUpload - Unable to select multiple files when trying consecutive attempts
We were trying to do a testing to support multiple file upload at different scenario's to suit our requirement. When we try to select the file for 2nd time, we are unable to select multiples file from the list. It allows only to choose single file but able to drag and drop multiple files. 

Browser used: Chrome v47.0.2526.106

It seems to be an issue. Request you to kindly check and update.

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**
Fix input field multiple files selection.

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Ok, UI now allows to select multiple files. But does the server side code handle them properly? Should we add a test case?

P.S. This PR reveals huge code duplication (line blocks 328-349 and 614-635). Not suggesting refactoring in this PR, but it's a good topic for another PR.

**Comment by MikhailTymchukDX** [comment]
>Ok, UI now allows to select multiple files.

It allowed doing that earlier, but only for the first time.

>But does the server side code handle them properly?

The server handles files one by one and does not know anything about the file queue.

>Should we add a test case?

Do you mean a client test that selects multiple files and upload it twice or server-side test?

**Comment by AlekseyMartynov** [comment]
> It allowed doing that earlier, but only for the first time.

I think I understand now. The server code renders the `multiple` attribute ([line 348](https://github.com/DevExpress/AjaxControlToolkit/blob/f5e6a67cc7217706cbe6e19d25cbe5991c9405e3/AjaxControlToolkit/AjaxFileUpload/AjaxFileUpload.cs#L348)), but the client script doesn't. The PR fixes the latter. Right?

**Comment by MikhailTymchukDX** [comment]
Yes.

**Comment by AlekseyMartynov** [comment]
:shipit:

**Pull request merged**
