### PR TITLE
ModalPopup - detachPopup can pop wrong item from the stack

### PR DESCRIPTION
**Pull request by 0bo0**
There are scenarios when detachPopup can be called without a prior call to attachPopup. In such case it removes parent popup from the stack.

### CODE REVIEW

**Comment by MikhailTymchukDX** [comment]
Hi @0bo0 ,
Thank you for the pull request!

I think moving `pop()` instruction into the condition block can produce unpredictable results.

Isn't is better to keep this line at the end of the method and check if the top popup equals the current one?

**Comment by 0bo0** [comment]
Hi @MikhailTymchukDX . This is exactly what I've done when I found the bug, but then I thought that it will be more elegant to move 'pop' to already existing 'if' block. It works well for me both ways, but if you prefer the option you suggested I can update the code.

**Comment by MikhailTymchukDX** [comment]
@0bo0 While your initial change produces the same result, I'd prefer an explicit check for a modal popup instance that is being removed.

**Comment by MikhailTymchukDX** [comment]
@0bo0 Thanks for the update.
To ensure that we are on the same page: what is your scenario where `_detachPopup()` can be called without a prior call of `_attachPopup()`, except for manually calling `_detachPopup()`?

**Comment by 0bo0** [comment]
@MikhailTymchukDX I haven't had time and need to build a test app but I think it happens when modalpopup control is dynamically loaded and unloaded in updatepanel (show() not called, controls removed from dom -> dispose() called). In my apps I have dynamically loaded multi-level nested popups with dynamic tabs from multiple ascxs so there's a chance the issue may be related to something else, but I think updatepanel explanation is highly probable.

**Pull request merged**
