### PR TITLE
Install NuGet 3.3

### PR DESCRIPTION
**Pull request by FeodorFitsner**

### CODE REVIEW

**Comment by MikhailTymchukDX** [comment]
Thank you for pull request, but we prefer to stay in stable build environment.

**Comment by MikhailTymchukDX** [comment]
Hi @FeodorFitsner,
Would you please re-submit this PR?
Also, I would like to ask you to update the [VS version in the solution file](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit.sln#L3-L4) to automatically [pick up MSBuild 14.0](http://help.appveyor.com/discussions/suggestions/772-use-msbuild-14-by-default):
```
# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
```

**Comment by FeodorFitsner** [comment]
Hi Mikhail,

Could you please clarify what would be the purpose/goal of this exercise? Are you having any issues/errors?

**Comment by AlekseyMartynov** [comment]
Hi @FeodorFitsner 
We apologize. No action is needed.
Thank you very much for the PR and for creating Appveyor! :smile: 

@MikhailTymchukDX 
Changes suggested by Feodor are useful. Please cherry-pick and integrate in a branch.

**Pull request closed without merging**
