### PR TITLE
ScriptUserControl added

### PR DESCRIPTION
**Pull request by tdjastrzebski**
It has been 3 years since I started to maintain a private version of AjaxControlToolkit just to have ScriptUserControl class in it allowing to extend user controls. This original functionality was never ported after when DevExpress took it over. Maybe, since the project is quite stable now, it is good time to include this class?

I do not want to discuss whether extending user controls is good idea or not. Let's just assume there are projects out there relaying on this functionality, complex enough that it makes more sense to maintain a separate AjaxControlToolkit version than recode.

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Would you please minimize the changeset?
https://github.com/DevExpress/AjaxControlToolkit/pull/347/files displays a bunch of changes due to different end-of-line style.

See https://help.github.com/articles/dealing-with-line-endings/

**Comment by tdjastrzebski** [comment]
Thank you, changeset has been reapplied.

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski
Thank you for contributing to the AJAX Control Toolkit!
 
We found that it would be possible to keep `ScriptUserControl` in a separate library without maintaining a fork if we publish the `ToolkitResourceManager.GetControlScriptReferences()` method and the `ScriptComponentDescriptorWrapper` class.
 
What do you think about this idea?
 
The only action that is needed on your side would be applying the `[ClientScriptResource(null, "BaseScripts")]` attribute to the `ScriptUserControl` class.
 
We are also concerned to hear about the `[TargetControlType(typeof(ScriptUserControl))]` attribute that is applied to a DropDownExtender.
We have no real-life example for that, so it would be very helpful if you provide us with a sample usage for this scenario, so we can test it with the proposed changes.

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX,

the approach you propose would work too.

Regarding the DropDownExtender: I agree. Perhaps `[TargetControlType(typeof(ScriptUserControl))]` should be applied to most of the extenders or none.

Typically, extenders can be applied to (Script)UserControls exactly the same way they can be applied to WebControls or HtmlControls. The common case is (Script)UserControl containing TextBox and common, preconfigured Validators which can be used across the project. With TargetControlType attribute applied to DropDownExtender such UserControl can be extended the same way simple TextBox can.

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski 

We made the proposed changes. Would you please get [the latest build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/build/artifacts) and check if everything works correctly on your side?

>Are you convinced almost all of the constants should be internal?

Yes, all constants remain internal.
In this simple case, it's OK to use a literal in an attribute.

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX,
one thing I have to figure out is how to load BaseScripts.js from the original AjaxControlToolkit assembly. Any suggestions?

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski 
You don't need to load it explicitly. This script is loaded automatically with the help of the [ToolkitResourceManager class](https://github.com/DevExpress/AjaxControlToolkit/blob/master/AjaxControlToolkit/ToolkitResourceManager.cs#L278).

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX,
I am not certain I understand. I tried to load BaseScripts.js declaratively using:
```[ClientScriptResource(null, "BaseScripts")]
public class ScriptUserControl : UserControl, IScriptControl, IControlResolver, IPostBackDataHandler, ICallbackEventHandler, IClientStateManager {...}```
This results in exception since the script is placed in another assembly resources.
Granted, in most cases the declaration is not needed as long as there is any other control used loading it but I would be good to be on the safe side. Do I miss anything?

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX what we need probably is something similar to [ASPxWebControl.RegisterBaseScript](https://documentation.devexpress.com/AspNet/DevExpress.Web.ASPxWebControl.RegisterBaseScript.overloads)

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski

Technically speaking, we can add a new property to the `ClientResource` attribute with an assembly name to resolve the script's assembly properly.
However, we cannot determine whether this script is mandatory for the `ScriptUserControl`.

Would you please provide us a sample project that demonstrates how `ScriptUserControl` is used so we can decide if it really needs BaseScripts?

**Comment by tdjastrzebski** [comment]
Hi @MikhailTymchukDX,

See a sample solution I posted a while ago - right in the middle of the discussion, link below.
[](https://forums.asp.net/t/1119462.aspx?How+to+preserve+my+Sys+UI+Control+properties+across+postbacks+)

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski 
Thank you very much for the sample!

We tried to run it with the provided implementation of the `ScriptUserControl` and ran into couple of issues.
To fix them, we tweaked `ToolkitResourceManager` implementation (see #371).

Now, to use BaseScripts in the `ScriptUserControl`, prepend the `ToolkitResourceManager.GetBaseScriptReference()` method call result to the `ToolkitResourceManager.GetControlScriptReferences()` call in `GetScriptReferences()` like this:

```csharp
protected virtual IEnumerable<ScriptReference> GetScriptReferences() {
    if(!Visible) return null;

    return new[] { ToolkitResourceManager.GetBaseScriptReference() }
        .Concat(ToolkitResourceManager.GetControlScriptReferences(GetType()));
}
```

Then, try using `ScriptUserControl` with [the latest AJAX Control Toolkit build](https://ci.appveyor.com/project/dxrobot/ajaxcontroltoolkit/branch/master/artifacts).

I look forward to your response.

**Comment by MikhailTymchukDX** [comment]
Hi @tdjastrzebski 
We assume that you are satisfied with these changes, so I merge this pull-request into the master branch.
If you have any info, feel free to comment.

**Comment by tdjastrzebski** [comment]
Thank you!

**Comment by tdjastrzebski** [comment]
I think ScriptUserControl class could be of use to others, especially those who would like to migrate from old ACT versions containing it. What would be the best way to share this class?

**Comment by MikhailTymchukDX** [comment]
@tdjastrzebski I believe the best way is to create a NuGet package and name it like "AjaxControlToolkit.ScriptUserControl", so people can find it easily.

**Comment by tdjastrzebski** [comment]
FYI: AjaxControlToolkit.ScriptUserControl has been published on GitHub

**Pull request closed without merging**
