### PR TITLE
Make SlideShow test condition more precise

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**
Previous one fails sometimes

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Looks good

**Comment by AlekseyMartynov** [comment]
> All checks have failed

Well, looks bad now :smile:

**Comment by MikhailTymchukDX** [comment]
Looks stable now.
/cc @AlekseyMartynov

**Comment by AlekseyMartynov** [comment]
Hope they are. Merge please.

**Pull request merged**
