### PR TITLE
Resolve #137

### LINKED ISSUE #137: Calendar extender not selecting years
When StartDate is setting for Calendar extender (in Properties or in program)  you cannot select other page in Year mode.  Version 16.0

### PR DESCRIPTION
**Pull request by MikhailTymchukDX**

### CODE REVIEW

**Comment by AlekseyMartynov** [comment]
Calendar rewritten from scratch :sweat_smile:

**Comment by Mehul** [comment]
Hooray? :)

**Comment by MikhailTymchukDX** [comment]
Extracting a method removed one level of indentation, so the diff looks weird. Apart from that, there are not so much changes.

**Comment by AlekseyMartynov** [comment]
@MikhailTymchukDX 
Calendar.js diff is quite massive. I can see some code style issues in it.

1. `Sys.Extended.UI.CalendarSwitchViewMode` (and other similar "enums") can be simplified to a plain object

    ```
    Sys.Extended.UI.CalendarSwitchViewMode = {
        PreviousRange: 0,
        NextRange: 1,
        RangeZoom: 2
    };
    ```

2. Wrong brace location for `_isInYearsDateRange`, `_getRangeStartYear`, `_animateViewSwitch`

3. Inconsistent line breaks around `else`

4. Really strange formatting here:
    ```
    if(startYear > this._startDate.getFullYear()
            &&
            endYear < this._endDate.getFullYear())
        return true;
    ```

**Comment by MikhailTymchukDX** [comment]
@AlekseyMartynov 
2, 4 - corrected.
1 - is it OK that this will be the only extender that defines enums in that way?
3 - I checked every `else` section: everything is surrounded with CR LF. Do you mean extra empty lines between braces?

**Comment by AlekseyMartynov** [comment]
> is it OK that this will be the only extender that defines enums in that way?

Why not. Good occasion to improve existing code along the way.

> Do you mean extra empty lines between braces?

I meant 
```
} else {
```
vs.
```
}
else {
```

**Comment by MikhailTymchukDX** [comment]
Done.

**Comment by AlekseyMartynov** [comment]
enum definitions lack trailing semicolon

**Comment by MikhailTymchukDX** [comment]
Fixed.

**Comment by AlekseyMartynov** [comment]
Ok, merge.

**Pull request merged**
